# coding: utf-8

"""
    Hermes Admin API

    Server-to-server API for managing notification groups, types, and sending notifications.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class CreateTypeInputBody(BaseModel):
    """
    CreateTypeInputBody
    """ # noqa: E501
    var_schema: Optional[StrictStr] = Field(default=None, description="A URL to the JSON Schema for this object.", alias="$schema")
    email_body: Optional[StrictStr] = Field(default=None, description="Email body template")
    email_subject: Optional[StrictStr] = Field(default=None, description="Email subject template")
    group_id: Annotated[str, Field(min_length=1, strict=True)] = Field(description="ID of the group this type belongs to")
    inbox_body: Optional[StrictStr] = Field(default=None, description="Inbox notification body template")
    inbox_title: Optional[StrictStr] = Field(default=None, description="Inbox notification title template")
    name: Annotated[str, Field(min_length=1, strict=True)] = Field(description="Human-readable name")
    slug: Annotated[str, Field(min_length=1, strict=True)] = Field(description="URL-friendly identifier")
    sms_body: Optional[StrictStr] = Field(default=None, description="SMS body template")
    __properties: ClassVar[List[str]] = ["$schema", "email_body", "email_subject", "group_id", "inbox_body", "inbox_title", "name", "slug", "sms_body"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateTypeInputBody from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "var_schema",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateTypeInputBody from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "$schema": obj.get("$schema"),
            "email_body": obj.get("email_body"),
            "email_subject": obj.get("email_subject"),
            "group_id": obj.get("group_id"),
            "inbox_body": obj.get("inbox_body"),
            "inbox_title": obj.get("inbox_title"),
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "sms_body": obj.get("sms_body")
        })
        return _obj


