FROM alpine:3.24
RUN apk --no-cache add ca-certificates tzdata
COPY migrations/ /migrations/
RUN mkdir /app && chown 65534:65534 /app
ARG SERVICE
COPY --chown=65534:65534 bin/${SERVICE}/service /app/service
USER 65534:65534
