apiVersion: batch/v1
kind: Job
metadata:
  name: hermes-migrate
  namespace: hermes
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: migrate
          image: hermes-migrate:latest
          args: ["-migrations-path", "/migrations"]
          envFrom:
            - configMapRef:
                name: hermes-config
          env:
            - name: HERMES_DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: hermes-config
                  key: HERMES_DATABASE_URL
      restartPolicy: Never
