apiVersion: v1
kind: Secret
metadata:
  name: hermes-secrets
  namespace: hermes
type: Opaque
stringData:
  HERMES_JWT_SECRET: "CHANGE-ME-jwt-secret"
  HERMES_CENTRIFUGO_TOKEN_SECRET: "CHANGE-ME-centrifugo-token-secret"
  HERMES_EMAIL_WEBHOOK_URL: "http://localhost:9090/email"
  HERMES_SMS_WEBHOOK_URL: "http://localhost:9090/sms"
