/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Hermes.ServerSdk.Api;
using Hermes.ServerSdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Hermes.ServerSdk.Test.Api
{
    /// <summary>
    ///  Class for testing OrganizationsApi
    /// </summary>
    public sealed class OrganizationsApiTests : ApiTestsBase
    {
        private readonly IOrganizationsApi _instance;

        public OrganizationsApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<IOrganizationsApi>();
        }

        /// <summary>
        /// Test CreateOrganization
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateOrganizationAsyncTest()
        {
            CreateOrganizationInputBody createOrganizationInputBody = default!;
            var response = await _instance.CreateOrganizationAsync(createOrganizationInputBody);
            var model = response.Created();
            Assert.IsType<OrganizationItem>(model);
        }

        /// <summary>
        /// Test ListOrganizations
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListOrganizationsAsyncTest()
        {
            var response = await _instance.ListOrganizationsAsync();
            var model = response.Ok();
            Assert.IsType<List<OrganizationItem>>(model);
        }
    }
}
