/*
 * Hermes Admin API
 *
 * Server-to-server API for managing notification groups, types, and sending notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Xunit;
using Microsoft.Extensions.DependencyInjection;
using Hermes.ServerSdk.Api;
using Hermes.ServerSdk.Model;


/* *********************************************************************************
*              Follow these manual steps to construct tests.
*              This file will not be overwritten.
*  *********************************************************************************
* 1. Navigate to ApiTests.Base.cs and ensure any tokens are being created correctly.
*    Take care not to commit credentials to any repository.
*
* 2. Mocking is coordinated by ApiTestsBase#AddApiHttpClients.
*    To mock the client, use the generic AddApiHttpClients.
*    To mock the server, change the client's BaseAddress.
*
* 3. Locate the test you want below
*      - remove the skip property from the Fact attribute
*      - set the value of any variables if necessary
*
* 4. Run the tests and ensure they work.
*
*/


namespace Hermes.ServerSdk.Test.Api
{
    /// <summary>
    ///  Class for testing TypesApi
    /// </summary>
    public sealed class TypesApiTests : ApiTestsBase
    {
        private readonly ITypesApi _instance;

        public TypesApiTests(): base(Array.Empty<string>())
        {
            _instance = _host.Services.GetRequiredService<ITypesApi>();
        }

        /// <summary>
        /// Test CreateType
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task CreateTypeAsyncTest()
        {
            CreateTypeInputBody createTypeInputBody = default!;
            var response = await _instance.CreateTypeAsync(createTypeInputBody);
            var model = response.Created();
            Assert.IsType<NotificationType>(model);
        }

        /// <summary>
        /// Test DeleteType
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task DeleteTypeAsyncTest()
        {
            string id = default!;
            await _instance.DeleteTypeAsync(id);
        }

        /// <summary>
        /// Test ListTypes
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task ListTypesAsyncTest()
        {
            var response = await _instance.ListTypesAsync();
            var model = response.Ok();
            Assert.IsType<List<NotificationType>>(model);
        }

        /// <summary>
        /// Test UpdateType
        /// </summary>
        [Fact (Skip = "not implemented")]
        public async Task UpdateTypeAsyncTest()
        {
            string id = default!;
            UpdateTypeInputBody updateTypeInputBody = default!;
            var response = await _instance.UpdateTypeAsync(id, updateTypeInputBody);
            var model = response.Ok();
            Assert.IsType<NotificationType>(model);
        }
    }
}
