apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-prometheus-stack-grafana
spec:
  template:
    spec:
      containers:
        - name: grafana
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-admin
                  key: admin-password
