apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: kps-prometheus
spec:
  retention: 3d
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 10Gi
