/*
 * Hermes Admin API
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hermes.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SetAPIKeyRateLimitInputBody
 */
public class SetAPIKeyRateLimitInputBodyTest {
    private final SetAPIKeyRateLimitInputBody model = new SetAPIKeyRateLimitInputBody();

    /**
     * Model tests for SetAPIKeyRateLimitInputBody
     */
    @Test
    public void testSetAPIKeyRateLimitInputBody() {
        // TODO: test SetAPIKeyRateLimitInputBody
    }

    /**
     * Test the property '$schema'
     */
    @Test
    public void $schemaTest() {
        // TODO: test $schema
    }

    /**
     * Test the property 'burst'
     */
    @Test
    public void burstTest() {
        // TODO: test burst
    }

    /**
     * Test the property 'perSecond'
     */
    @Test
    public void perSecondTest() {
        // TODO: test perSecond
    }

}
