/*
 * Hermes Admin API
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hermes.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UpdateCategoryInputBody
 */
public class UpdateCategoryInputBodyTest {
    private final UpdateCategoryInputBody model = new UpdateCategoryInputBody();

    /**
     * Model tests for UpdateCategoryInputBody
     */
    @Test
    public void testUpdateCategoryInputBody() {
        // TODO: test UpdateCategoryInputBody
    }

    /**
     * Test the property '$schema'
     */
    @Test
    public void $schemaTest() {
        // TODO: test $schema
    }

    /**
     * Test the property 'defaultChannels'
     */
    @Test
    public void defaultChannelsTest() {
        // TODO: test defaultChannels
    }

    /**
     * Test the property 'defaultState'
     */
    @Test
    public void defaultStateTest() {
        // TODO: test defaultState
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'sortOrder'
     */
    @Test
    public void sortOrderTest() {
        // TODO: test sortOrder
    }

}
