// <auto-generated>
/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Hermes.ServerSdk.Client;

namespace Hermes.ServerSdk.Model
{
    /// <summary>
    /// Notification
    /// </summary>
    public partial class Notification : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Notification" /> class.
        /// </summary>
        /// <param name="body">body</param>
        /// <param name="categoryId">categoryId</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="id">id</param>
        /// <param name="organizationId">organizationId</param>
        /// <param name="status">status</param>
        /// <param name="title">title</param>
        /// <param name="userId">userId</param>
        /// <param name="actionLabel">actionLabel</param>
        /// <param name="actionUrl">actionUrl</param>
        /// <param name="archivedAt">archivedAt</param>
        /// <param name="channels">channels</param>
        /// <param name="deletedAt">deletedAt</param>
        /// <param name="deliveredAt">deliveredAt</param>
        /// <param name="idempotencyKey">idempotencyKey</param>
        /// <param name="readAt">readAt</param>
        /// <param name="sentAt">sentAt</param>
        /// <param name="templateId">templateId</param>
        [JsonConstructor]
        public Notification(string body, string categoryId, DateTime createdAt, string id, string organizationId, string status, string title, string userId, Option<string?> actionLabel = default, Option<string?> actionUrl = default, Option<DateTime?> archivedAt = default, List<string>? channels = default, Option<DateTime?> deletedAt = default, Option<DateTime?> deliveredAt = default, Option<string?> idempotencyKey = default, Option<DateTime?> readAt = default, Option<DateTime?> sentAt = default, Option<string?> templateId = default)
        {
            Body = body;
            CategoryId = categoryId;
            CreatedAt = createdAt;
            Id = id;
            OrganizationId = organizationId;
            Status = status;
            Title = title;
            UserId = userId;
            ActionLabelOption = actionLabel;
            ActionUrlOption = actionUrl;
            ArchivedAtOption = archivedAt;
            Channels = channels;
            DeletedAtOption = deletedAt;
            DeliveredAtOption = deliveredAt;
            IdempotencyKeyOption = idempotencyKey;
            ReadAtOption = readAt;
            SentAtOption = sentAt;
            TemplateIdOption = templateId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Body
        /// </summary>
        [JsonPropertyName("body")]
        public string Body { get; set; }

        /// <summary>
        /// Gets or Sets CategoryId
        /// </summary>
        [JsonPropertyName("category_id")]
        public string CategoryId { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets OrganizationId
        /// </summary>
        [JsonPropertyName("organization_id")]
        public string OrganizationId { get; set; }

        /// <summary>
        /// Gets or Sets Status
        /// </summary>
        [JsonPropertyName("status")]
        public string Status { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("user_id")]
        public string UserId { get; set; }

        /// <summary>
        /// Used to track the state of ActionLabel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActionLabelOption { get; private set; }

        /// <summary>
        /// Gets or Sets ActionLabel
        /// </summary>
        [JsonPropertyName("action_label")]
        public string? ActionLabel { get { return this.ActionLabelOption; } set { this.ActionLabelOption = new(value); } }

        /// <summary>
        /// Used to track the state of ActionUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActionUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets ActionUrl
        /// </summary>
        [JsonPropertyName("action_url")]
        public string? ActionUrl { get { return this.ActionUrlOption; } set { this.ActionUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of ArchivedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ArchivedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ArchivedAt
        /// </summary>
        [JsonPropertyName("archived_at")]
        public DateTime? ArchivedAt { get { return this.ArchivedAtOption; } set { this.ArchivedAtOption = new(value); } }

        /// <summary>
        /// Gets or Sets Channels
        /// </summary>
        [JsonPropertyName("channels")]
        public List<string>? Channels { get; set; }

        /// <summary>
        /// Used to track the state of DeletedAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DeletedAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets DeletedAt
        /// </summary>
        [JsonPropertyName("deleted_at")]
        public DateTime? DeletedAt { get { return this.DeletedAtOption; } set { this.DeletedAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of DeliveredAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> DeliveredAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets DeliveredAt
        /// </summary>
        [JsonPropertyName("delivered_at")]
        public DateTime? DeliveredAt { get { return this.DeliveredAtOption; } set { this.DeliveredAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of IdempotencyKey
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> IdempotencyKeyOption { get; private set; }

        /// <summary>
        /// Gets or Sets IdempotencyKey
        /// </summary>
        [JsonPropertyName("idempotency_key")]
        public string? IdempotencyKey { get { return this.IdempotencyKeyOption; } set { this.IdempotencyKeyOption = new(value); } }

        /// <summary>
        /// Used to track the state of ReadAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> ReadAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets ReadAt
        /// </summary>
        [JsonPropertyName("read_at")]
        public DateTime? ReadAt { get { return this.ReadAtOption; } set { this.ReadAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of SentAt
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> SentAtOption { get; private set; }

        /// <summary>
        /// Gets or Sets SentAt
        /// </summary>
        [JsonPropertyName("sent_at")]
        public DateTime? SentAt { get { return this.SentAtOption; } set { this.SentAtOption = new(value); } }

        /// <summary>
        /// Used to track the state of TemplateId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TemplateIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets TemplateId
        /// </summary>
        [JsonPropertyName("template_id")]
        public string? TemplateId { get { return this.TemplateIdOption; } set { this.TemplateIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Notification {\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  CategoryId: ").Append(CategoryId).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  OrganizationId: ").Append(OrganizationId).Append("\n");
            sb.Append("  Status: ").Append(Status).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  ActionLabel: ").Append(ActionLabel).Append("\n");
            sb.Append("  ActionUrl: ").Append(ActionUrl).Append("\n");
            sb.Append("  ArchivedAt: ").Append(ArchivedAt).Append("\n");
            sb.Append("  Channels: ").Append(Channels).Append("\n");
            sb.Append("  DeletedAt: ").Append(DeletedAt).Append("\n");
            sb.Append("  DeliveredAt: ").Append(DeliveredAt).Append("\n");
            sb.Append("  IdempotencyKey: ").Append(IdempotencyKey).Append("\n");
            sb.Append("  ReadAt: ").Append(ReadAt).Append("\n");
            sb.Append("  SentAt: ").Append(SentAt).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="Notification" />
    /// </summary>
    public class NotificationJsonConverter : JsonConverter<Notification>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ArchivedAt
        /// </summary>
        public static string ArchivedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize DeletedAt
        /// </summary>
        public static string DeletedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize DeliveredAt
        /// </summary>
        public static string DeliveredAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize ReadAt
        /// </summary>
        public static string ReadAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// The format to use to serialize SentAt
        /// </summary>
        public static string SentAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="Notification" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override Notification Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> body = default;
            Option<string?> categoryId = default;
            Option<DateTime?> createdAt = default;
            Option<string?> id = default;
            Option<string?> organizationId = default;
            Option<string?> status = default;
            Option<string?> title = default;
            Option<string?> userId = default;
            Option<string?> actionLabel = default;
            Option<string?> actionUrl = default;
            Option<DateTime?> archivedAt = default;
            Option<List<string>?> channels = default;
            Option<DateTime?> deletedAt = default;
            Option<DateTime?> deliveredAt = default;
            Option<string?> idempotencyKey = default;
            Option<DateTime?> readAt = default;
            Option<DateTime?> sentAt = default;
            Option<string?> templateId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "body":
                            body = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "category_id":
                            categoryId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "organization_id":
                            organizationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "status":
                            status = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_id":
                            userId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action_label":
                            actionLabel = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action_url":
                            actionUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "archived_at":
                            archivedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "channels":
                            channels = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "deleted_at":
                            deletedAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "delivered_at":
                            deliveredAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "idempotency_key":
                            idempotencyKey = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "read_at":
                            readAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "sent_at":
                            sentAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "template_id":
                            templateId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!body.IsSet)
                throw new ArgumentException("Property is required for class Notification.", nameof(body));

            if (!categoryId.IsSet)
                throw new ArgumentException("Property is required for class Notification.", nameof(categoryId));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class Notification.", nameof(createdAt));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class Notification.", nameof(id));

            if (!organizationId.IsSet)
                throw new ArgumentException("Property is required for class Notification.", nameof(organizationId));

            if (!status.IsSet)
                throw new ArgumentException("Property is required for class Notification.", nameof(status));

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class Notification.", nameof(title));

            if (!userId.IsSet)
                throw new ArgumentException("Property is required for class Notification.", nameof(userId));

            if (!channels.IsSet)
                throw new ArgumentException("Property is required for class Notification.", nameof(channels));

            if (body.IsSet && body.Value == null)
                throw new ArgumentNullException(nameof(body), "Property is not nullable for class Notification.");

            if (categoryId.IsSet && categoryId.Value == null)
                throw new ArgumentNullException(nameof(categoryId), "Property is not nullable for class Notification.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class Notification.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class Notification.");

            if (organizationId.IsSet && organizationId.Value == null)
                throw new ArgumentNullException(nameof(organizationId), "Property is not nullable for class Notification.");

            if (status.IsSet && status.Value == null)
                throw new ArgumentNullException(nameof(status), "Property is not nullable for class Notification.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class Notification.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class Notification.");

            if (actionLabel.IsSet && actionLabel.Value == null)
                throw new ArgumentNullException(nameof(actionLabel), "Property is not nullable for class Notification.");

            if (actionUrl.IsSet && actionUrl.Value == null)
                throw new ArgumentNullException(nameof(actionUrl), "Property is not nullable for class Notification.");

            if (archivedAt.IsSet && archivedAt.Value == null)
                throw new ArgumentNullException(nameof(archivedAt), "Property is not nullable for class Notification.");

            if (deletedAt.IsSet && deletedAt.Value == null)
                throw new ArgumentNullException(nameof(deletedAt), "Property is not nullable for class Notification.");

            if (deliveredAt.IsSet && deliveredAt.Value == null)
                throw new ArgumentNullException(nameof(deliveredAt), "Property is not nullable for class Notification.");

            if (idempotencyKey.IsSet && idempotencyKey.Value == null)
                throw new ArgumentNullException(nameof(idempotencyKey), "Property is not nullable for class Notification.");

            if (readAt.IsSet && readAt.Value == null)
                throw new ArgumentNullException(nameof(readAt), "Property is not nullable for class Notification.");

            if (sentAt.IsSet && sentAt.Value == null)
                throw new ArgumentNullException(nameof(sentAt), "Property is not nullable for class Notification.");

            if (templateId.IsSet && templateId.Value == null)
                throw new ArgumentNullException(nameof(templateId), "Property is not nullable for class Notification.");

            return new Notification(body.Value!, categoryId.Value!, createdAt.Value!.Value!, id.Value!, organizationId.Value!, status.Value!, title.Value!, userId.Value!, actionLabel, actionUrl, archivedAt, channels.Value!, deletedAt, deliveredAt, idempotencyKey, readAt, sentAt, templateId);
        }

        /// <summary>
        /// Serializes a <see cref="Notification" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notification"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, Notification notification, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, notification, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="Notification" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notification"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, Notification notification, JsonSerializerOptions jsonSerializerOptions)
        {
            if (notification.Body == null)
                throw new ArgumentNullException(nameof(notification.Body), "Property is required for class Notification.");

            if (notification.CategoryId == null)
                throw new ArgumentNullException(nameof(notification.CategoryId), "Property is required for class Notification.");

            if (notification.Id == null)
                throw new ArgumentNullException(nameof(notification.Id), "Property is required for class Notification.");

            if (notification.OrganizationId == null)
                throw new ArgumentNullException(nameof(notification.OrganizationId), "Property is required for class Notification.");

            if (notification.Status == null)
                throw new ArgumentNullException(nameof(notification.Status), "Property is required for class Notification.");

            if (notification.Title == null)
                throw new ArgumentNullException(nameof(notification.Title), "Property is required for class Notification.");

            if (notification.UserId == null)
                throw new ArgumentNullException(nameof(notification.UserId), "Property is required for class Notification.");

            if (notification.ActionLabelOption.IsSet && notification.ActionLabel == null)
                throw new ArgumentNullException(nameof(notification.ActionLabel), "Property is required for class Notification.");

            if (notification.ActionUrlOption.IsSet && notification.ActionUrl == null)
                throw new ArgumentNullException(nameof(notification.ActionUrl), "Property is required for class Notification.");

            if (notification.IdempotencyKeyOption.IsSet && notification.IdempotencyKey == null)
                throw new ArgumentNullException(nameof(notification.IdempotencyKey), "Property is required for class Notification.");

            if (notification.TemplateIdOption.IsSet && notification.TemplateId == null)
                throw new ArgumentNullException(nameof(notification.TemplateId), "Property is required for class Notification.");

            writer.WriteString("body", notification.Body);

            writer.WriteString("category_id", notification.CategoryId);

            writer.WriteString("created_at", notification.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("id", notification.Id);

            writer.WriteString("organization_id", notification.OrganizationId);

            writer.WriteString("status", notification.Status);

            writer.WriteString("title", notification.Title);

            writer.WriteString("user_id", notification.UserId);

            if (notification.ActionLabelOption.IsSet)
                writer.WriteString("action_label", notification.ActionLabel);

            if (notification.ActionUrlOption.IsSet)
                writer.WriteString("action_url", notification.ActionUrl);

            if (notification.ArchivedAtOption.IsSet)
                writer.WriteString("archived_at", notification.ArchivedAtOption.Value!.Value.ToString(ArchivedAtFormat));

            if (notification.Channels != null)
            {
                writer.WritePropertyName("channels");
                JsonSerializer.Serialize(writer, notification.Channels, jsonSerializerOptions);
            }
            else
                writer.WriteNull("channels");
            if (notification.DeletedAtOption.IsSet)
                writer.WriteString("deleted_at", notification.DeletedAtOption.Value!.Value.ToString(DeletedAtFormat));

            if (notification.DeliveredAtOption.IsSet)
                writer.WriteString("delivered_at", notification.DeliveredAtOption.Value!.Value.ToString(DeliveredAtFormat));

            if (notification.IdempotencyKeyOption.IsSet)
                writer.WriteString("idempotency_key", notification.IdempotencyKey);

            if (notification.ReadAtOption.IsSet)
                writer.WriteString("read_at", notification.ReadAtOption.Value!.Value.ToString(ReadAtFormat));

            if (notification.SentAtOption.IsSet)
                writer.WriteString("sent_at", notification.SentAtOption.Value!.Value.ToString(SentAtFormat));

            if (notification.TemplateIdOption.IsSet)
                writer.WriteString("template_id", notification.TemplateId);
        }
    }
}
