// <auto-generated>
/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Hermes.ServerSdk.Client;

namespace Hermes.ServerSdk.Model
{
    /// <summary>
    /// NotificationEvent
    /// </summary>
    public partial class NotificationEvent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NotificationEvent" /> class.
        /// </summary>
        /// <param name="channel">channel</param>
        /// <param name="createdAt">createdAt</param>
        /// <param name="event">event</param>
        /// <param name="id">id</param>
        /// <param name="notificationId">notificationId</param>
        /// <param name="severity">severity</param>
        /// <param name="metadata">metadata</param>
        [JsonConstructor]
        public NotificationEvent(string channel, DateTime createdAt, string @event, string id, string notificationId, string severity, Option<Object?> metadata = default)
        {
            Channel = channel;
            CreatedAt = createdAt;
            Event = @event;
            Id = id;
            NotificationId = notificationId;
            Severity = severity;
            MetadataOption = metadata;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets Channel
        /// </summary>
        [JsonPropertyName("channel")]
        public string Channel { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets Event
        /// </summary>
        [JsonPropertyName("event")]
        public string Event { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets NotificationId
        /// </summary>
        [JsonPropertyName("notification_id")]
        public string NotificationId { get; set; }

        /// <summary>
        /// Gets or Sets Severity
        /// </summary>
        [JsonPropertyName("severity")]
        public string Severity { get; set; }

        /// <summary>
        /// Used to track the state of Metadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> MetadataOption { get; private set; }

        /// <summary>
        /// Gets or Sets Metadata
        /// </summary>
        [JsonPropertyName("metadata")]
        public Object? Metadata { get { return this.MetadataOption; } set { this.MetadataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NotificationEvent {\n");
            sb.Append("  Channel: ").Append(Channel).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  Event: ").Append(Event).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  NotificationId: ").Append(NotificationId).Append("\n");
            sb.Append("  Severity: ").Append(Severity).Append("\n");
            sb.Append("  Metadata: ").Append(Metadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NotificationEvent" />
    /// </summary>
    public class NotificationEventJsonConverter : JsonConverter<NotificationEvent>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="NotificationEvent" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NotificationEvent Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> channel = default;
            Option<DateTime?> createdAt = default;
            Option<string?> varEvent = default;
            Option<string?> id = default;
            Option<string?> notificationId = default;
            Option<string?> severity = default;
            Option<Object?> metadata = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "channel":
                            channel = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "event":
                            varEvent = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "notification_id":
                            notificationId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "severity":
                            severity = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "metadata":
                            metadata = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!channel.IsSet)
                throw new ArgumentException("Property is required for class NotificationEvent.", nameof(channel));

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class NotificationEvent.", nameof(createdAt));

            if (!varEvent.IsSet)
                throw new ArgumentException("Property is required for class NotificationEvent.", nameof(varEvent));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class NotificationEvent.", nameof(id));

            if (!notificationId.IsSet)
                throw new ArgumentException("Property is required for class NotificationEvent.", nameof(notificationId));

            if (!severity.IsSet)
                throw new ArgumentException("Property is required for class NotificationEvent.", nameof(severity));

            if (channel.IsSet && channel.Value == null)
                throw new ArgumentNullException(nameof(channel), "Property is not nullable for class NotificationEvent.");

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class NotificationEvent.");

            if (varEvent.IsSet && varEvent.Value == null)
                throw new ArgumentNullException(nameof(varEvent), "Property is not nullable for class NotificationEvent.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class NotificationEvent.");

            if (notificationId.IsSet && notificationId.Value == null)
                throw new ArgumentNullException(nameof(notificationId), "Property is not nullable for class NotificationEvent.");

            if (severity.IsSet && severity.Value == null)
                throw new ArgumentNullException(nameof(severity), "Property is not nullable for class NotificationEvent.");

            return new NotificationEvent(channel.Value!, createdAt.Value!.Value!, varEvent.Value!, id.Value!, notificationId.Value!, severity.Value!, metadata);
        }

        /// <summary>
        /// Serializes a <see cref="NotificationEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notificationEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NotificationEvent notificationEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, notificationEvent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NotificationEvent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="notificationEvent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NotificationEvent notificationEvent, JsonSerializerOptions jsonSerializerOptions)
        {
            if (notificationEvent.Channel == null)
                throw new ArgumentNullException(nameof(notificationEvent.Channel), "Property is required for class NotificationEvent.");

            if (notificationEvent.Event == null)
                throw new ArgumentNullException(nameof(notificationEvent.Event), "Property is required for class NotificationEvent.");

            if (notificationEvent.Id == null)
                throw new ArgumentNullException(nameof(notificationEvent.Id), "Property is required for class NotificationEvent.");

            if (notificationEvent.NotificationId == null)
                throw new ArgumentNullException(nameof(notificationEvent.NotificationId), "Property is required for class NotificationEvent.");

            if (notificationEvent.Severity == null)
                throw new ArgumentNullException(nameof(notificationEvent.Severity), "Property is required for class NotificationEvent.");

            writer.WriteString("channel", notificationEvent.Channel);

            writer.WriteString("created_at", notificationEvent.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("event", notificationEvent.Event);

            writer.WriteString("id", notificationEvent.Id);

            writer.WriteString("notification_id", notificationEvent.NotificationId);

            writer.WriteString("severity", notificationEvent.Severity);

            if (notificationEvent.MetadataOption.IsSet)
                if (notificationEvent.MetadataOption.Value != null)
                {
                    writer.WritePropertyName("metadata");
                    JsonSerializer.Serialize(writer, notificationEvent.Metadata, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("metadata");
        }
    }
}
