// <auto-generated>
/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Hermes.ServerSdk.Client;

namespace Hermes.ServerSdk.Model
{
    /// <summary>
    /// OrganizationItem
    /// </summary>
    public partial class OrganizationItem : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrganizationItem" /> class.
        /// </summary>
        /// <param name="createdAt">createdAt</param>
        /// <param name="defaultLocale">defaultLocale</param>
        /// <param name="id">id</param>
        /// <param name="name">name</param>
        /// <param name="userCount">userCount</param>
        /// <param name="schema">A URL to the JSON Schema for this object.</param>
        [JsonConstructor]
        public OrganizationItem(DateTime createdAt, string defaultLocale, string id, string name, long userCount, Option<string?> schema = default)
        {
            CreatedAt = createdAt;
            DefaultLocale = defaultLocale;
            Id = id;
            Name = name;
            UserCount = userCount;
            SchemaOption = schema;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [JsonPropertyName("created_at")]
        public DateTime CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets DefaultLocale
        /// </summary>
        [JsonPropertyName("default_locale")]
        public string DefaultLocale { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets UserCount
        /// </summary>
        [JsonPropertyName("user_count")]
        public long UserCount { get; set; }

        /// <summary>
        /// Used to track the state of Schema
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SchemaOption { get; }

        /// <summary>
        /// A URL to the JSON Schema for this object.
        /// </summary>
        /// <value>A URL to the JSON Schema for this object.</value>
        [JsonPropertyName("$schema")]
        public string? Schema { get { return this.SchemaOption; } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class OrganizationItem {\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  DefaultLocale: ").Append(DefaultLocale).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  UserCount: ").Append(UserCount).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="OrganizationItem" />
    /// </summary>
    public class OrganizationItemJsonConverter : JsonConverter<OrganizationItem>
    {
        /// <summary>
        /// The format to use to serialize CreatedAt
        /// </summary>
        public static string CreatedAtFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="OrganizationItem" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override OrganizationItem Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateTime?> createdAt = default;
            Option<string?> defaultLocale = default;
            Option<string?> id = default;
            Option<string?> name = default;
            Option<long?> userCount = default;
            Option<string?> schema = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "created_at":
                            createdAt = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "default_locale":
                            defaultLocale = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "id":
                            id = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "user_count":
                            userCount = new Option<long?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (long?)null : utf8JsonReader.GetInt64());
                            break;
                        case "$schema":
                            schema = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!createdAt.IsSet)
                throw new ArgumentException("Property is required for class OrganizationItem.", nameof(createdAt));

            if (!defaultLocale.IsSet)
                throw new ArgumentException("Property is required for class OrganizationItem.", nameof(defaultLocale));

            if (!id.IsSet)
                throw new ArgumentException("Property is required for class OrganizationItem.", nameof(id));

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class OrganizationItem.", nameof(name));

            if (!userCount.IsSet)
                throw new ArgumentException("Property is required for class OrganizationItem.", nameof(userCount));

            if (createdAt.IsSet && createdAt.Value == null)
                throw new ArgumentNullException(nameof(createdAt), "Property is not nullable for class OrganizationItem.");

            if (defaultLocale.IsSet && defaultLocale.Value == null)
                throw new ArgumentNullException(nameof(defaultLocale), "Property is not nullable for class OrganizationItem.");

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class OrganizationItem.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class OrganizationItem.");

            if (userCount.IsSet && userCount.Value == null)
                throw new ArgumentNullException(nameof(userCount), "Property is not nullable for class OrganizationItem.");

            if (schema.IsSet && schema.Value == null)
                throw new ArgumentNullException(nameof(schema), "Property is not nullable for class OrganizationItem.");

            return new OrganizationItem(createdAt.Value!.Value!, defaultLocale.Value!, id.Value!, name.Value!, userCount.Value!.Value!, schema);
        }

        /// <summary>
        /// Serializes a <see cref="OrganizationItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="organizationItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, OrganizationItem organizationItem, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, organizationItem, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="OrganizationItem" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="organizationItem"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, OrganizationItem organizationItem, JsonSerializerOptions jsonSerializerOptions)
        {
            if (organizationItem.DefaultLocale == null)
                throw new ArgumentNullException(nameof(organizationItem.DefaultLocale), "Property is required for class OrganizationItem.");

            if (organizationItem.Id == null)
                throw new ArgumentNullException(nameof(organizationItem.Id), "Property is required for class OrganizationItem.");

            if (organizationItem.Name == null)
                throw new ArgumentNullException(nameof(organizationItem.Name), "Property is required for class OrganizationItem.");

            if (organizationItem.SchemaOption.IsSet && organizationItem.Schema == null)
                throw new ArgumentNullException(nameof(organizationItem.Schema), "Property is required for class OrganizationItem.");

            writer.WriteString("created_at", organizationItem.CreatedAt.ToString(CreatedAtFormat));

            writer.WriteString("default_locale", organizationItem.DefaultLocale);

            writer.WriteString("id", organizationItem.Id);

            writer.WriteString("name", organizationItem.Name);

            writer.WriteNumber("user_count", organizationItem.UserCount);

            if (organizationItem.SchemaOption.IsSet)
                writer.WriteString("$schema", organizationItem.Schema);
        }
    }
}
