// <auto-generated>
/*
 * Hermes Admin API
 *
 * Server-to-server API for managing notification groups, types, and sending notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Hermes.ServerSdk.Client;

namespace Hermes.ServerSdk.Model
{
    /// <summary>
    /// SendContent
    /// </summary>
    public partial class SendContent : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SendContent" /> class.
        /// </summary>
        /// <param name="body">Notification body</param>
        /// <param name="title">Notification title</param>
        /// <param name="actionLabel">Optional action button label</param>
        /// <param name="actionUrl">Optional action URL</param>
        [JsonConstructor]
        public SendContent(string body, string title, Option<string?> actionLabel = default, Option<string?> actionUrl = default)
        {
            Body = body;
            Title = title;
            ActionLabelOption = actionLabel;
            ActionUrlOption = actionUrl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Notification body
        /// </summary>
        /// <value>Notification body</value>
        [JsonPropertyName("body")]
        public string Body { get; set; }

        /// <summary>
        /// Notification title
        /// </summary>
        /// <value>Notification title</value>
        [JsonPropertyName("title")]
        public string Title { get; set; }

        /// <summary>
        /// Used to track the state of ActionLabel
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActionLabelOption { get; private set; }

        /// <summary>
        /// Optional action button label
        /// </summary>
        /// <value>Optional action button label</value>
        [JsonPropertyName("action_label")]
        public string? ActionLabel { get { return this.ActionLabelOption; } set { this.ActionLabelOption = new(value); } }

        /// <summary>
        /// Used to track the state of ActionUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ActionUrlOption { get; private set; }

        /// <summary>
        /// Optional action URL
        /// </summary>
        /// <value>Optional action URL</value>
        [JsonPropertyName("action_url")]
        public string? ActionUrl { get { return this.ActionUrlOption; } set { this.ActionUrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SendContent {\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  ActionLabel: ").Append(ActionLabel).Append("\n");
            sb.Append("  ActionUrl: ").Append(ActionUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SendContent" />
    /// </summary>
    public class SendContentJsonConverter : JsonConverter<SendContent>
    {
        /// <summary>
        /// Deserializes json to <see cref="SendContent" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SendContent Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> body = default;
            Option<string?> title = default;
            Option<string?> actionLabel = default;
            Option<string?> actionUrl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "body":
                            body = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action_label":
                            actionLabel = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "action_url":
                            actionUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!body.IsSet)
                throw new ArgumentException("Property is required for class SendContent.", nameof(body));

            if (!title.IsSet)
                throw new ArgumentException("Property is required for class SendContent.", nameof(title));

            if (body.IsSet && body.Value == null)
                throw new ArgumentNullException(nameof(body), "Property is not nullable for class SendContent.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class SendContent.");

            if (actionLabel.IsSet && actionLabel.Value == null)
                throw new ArgumentNullException(nameof(actionLabel), "Property is not nullable for class SendContent.");

            if (actionUrl.IsSet && actionUrl.Value == null)
                throw new ArgumentNullException(nameof(actionUrl), "Property is not nullable for class SendContent.");

            return new SendContent(body.Value!, title.Value!, actionLabel, actionUrl);
        }

        /// <summary>
        /// Serializes a <see cref="SendContent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendContent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SendContent sendContent, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, sendContent, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SendContent" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="sendContent"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SendContent sendContent, JsonSerializerOptions jsonSerializerOptions)
        {
            if (sendContent.Body == null)
                throw new ArgumentNullException(nameof(sendContent.Body), "Property is required for class SendContent.");

            if (sendContent.Title == null)
                throw new ArgumentNullException(nameof(sendContent.Title), "Property is required for class SendContent.");

            if (sendContent.ActionLabelOption.IsSet && sendContent.ActionLabel == null)
                throw new ArgumentNullException(nameof(sendContent.ActionLabel), "Property is required for class SendContent.");

            if (sendContent.ActionUrlOption.IsSet && sendContent.ActionUrl == null)
                throw new ArgumentNullException(nameof(sendContent.ActionUrl), "Property is required for class SendContent.");

            writer.WriteString("body", sendContent.Body);

            writer.WriteString("title", sendContent.Title);

            if (sendContent.ActionLabelOption.IsSet)
                writer.WriteString("action_label", sendContent.ActionLabel);

            if (sendContent.ActionUrlOption.IsSet)
                writer.WriteString("action_url", sendContent.ActionUrl);
        }
    }
}
