// <auto-generated>
/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Hermes.ServerSdk.Client;

namespace Hermes.ServerSdk.Model
{
    /// <summary>
    /// UpdateTemplateInputBody
    /// </summary>
    public partial class UpdateTemplateInputBody : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UpdateTemplateInputBody" /> class.
        /// </summary>
        /// <param name="name">Human-readable name</param>
        /// <param name="schema">A URL to the JSON Schema for this object.</param>
        /// <param name="content">Per-channel content: channel slug -&gt; field key -&gt; template string (e.g. {\&quot;email\&quot;:{\&quot;subject\&quot;:\&quot;...\&quot;,\&quot;body\&quot;:\&quot;...\&quot;}})</param>
        /// <param name="defaultChannels">Default channels (used when no subscription)</param>
        /// <param name="subscriptionId">Subscription ID (null for standalone)</param>
        [JsonConstructor]
        public UpdateTemplateInputBody(string name, Option<string?> schema = default, Option<Dictionary<string, Dictionary<string, string>>?> content = default, Option<List<string>?> defaultChannels = default, Option<string?> subscriptionId = default)
        {
            Name = name;
            SchemaOption = schema;
            ContentOption = content;
            DefaultChannelsOption = defaultChannels;
            SubscriptionIdOption = subscriptionId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Human-readable name
        /// </summary>
        /// <value>Human-readable name</value>
        [JsonPropertyName("name")]
        public string Name { get; set; }

        /// <summary>
        /// Used to track the state of Schema
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SchemaOption { get; }

        /// <summary>
        /// A URL to the JSON Schema for this object.
        /// </summary>
        /// <value>A URL to the JSON Schema for this object.</value>
        [JsonPropertyName("$schema")]
        public string? Schema { get { return this.SchemaOption; } }

        /// <summary>
        /// Used to track the state of Content
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Dictionary<string, Dictionary<string, string>>?> ContentOption { get; private set; }

        /// <summary>
        /// Per-channel content: channel slug -&gt; field key -&gt; template string (e.g. {\&quot;email\&quot;:{\&quot;subject\&quot;:\&quot;...\&quot;,\&quot;body\&quot;:\&quot;...\&quot;}})
        /// </summary>
        /// <value>Per-channel content: channel slug -&gt; field key -&gt; template string (e.g. {\&quot;email\&quot;:{\&quot;subject\&quot;:\&quot;...\&quot;,\&quot;body\&quot;:\&quot;...\&quot;}})</value>
        [JsonPropertyName("content")]
        public Dictionary<string, Dictionary<string, string>>? Content { get { return this.ContentOption; } set { this.ContentOption = new(value); } }

        /// <summary>
        /// Used to track the state of DefaultChannels
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<string>?> DefaultChannelsOption { get; private set; }

        /// <summary>
        /// Default channels (used when no subscription)
        /// </summary>
        /// <value>Default channels (used when no subscription)</value>
        [JsonPropertyName("default_channels")]
        public List<string>? DefaultChannels { get { return this.DefaultChannelsOption; } set { this.DefaultChannelsOption = new(value); } }

        /// <summary>
        /// Used to track the state of SubscriptionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SubscriptionIdOption { get; private set; }

        /// <summary>
        /// Subscription ID (null for standalone)
        /// </summary>
        /// <value>Subscription ID (null for standalone)</value>
        [JsonPropertyName("subscription_id")]
        public string? SubscriptionId { get { return this.SubscriptionIdOption; } set { this.SubscriptionIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UpdateTemplateInputBody {\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Schema: ").Append(Schema).Append("\n");
            sb.Append("  Content: ").Append(Content).Append("\n");
            sb.Append("  DefaultChannels: ").Append(DefaultChannels).Append("\n");
            sb.Append("  SubscriptionId: ").Append(SubscriptionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="UpdateTemplateInputBody" />
    /// </summary>
    public class UpdateTemplateInputBodyJsonConverter : JsonConverter<UpdateTemplateInputBody>
    {
        /// <summary>
        /// Deserializes json to <see cref="UpdateTemplateInputBody" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override UpdateTemplateInputBody Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> name = default;
            Option<string?> schema = default;
            Option<Dictionary<string, Dictionary<string, string>>?> content = default;
            Option<List<string>?> defaultChannels = default;
            Option<string?> subscriptionId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "$schema":
                            schema = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "content":
                            content = new Option<Dictionary<string, Dictionary<string, string>>?>(JsonSerializer.Deserialize<Dictionary<string, Dictionary<string, string>>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "default_channels":
                            defaultChannels = new Option<List<string>?>(JsonSerializer.Deserialize<List<string>>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        case "subscription_id":
                            subscriptionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (!name.IsSet)
                throw new ArgumentException("Property is required for class UpdateTemplateInputBody.", nameof(name));

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class UpdateTemplateInputBody.");

            if (schema.IsSet && schema.Value == null)
                throw new ArgumentNullException(nameof(schema), "Property is not nullable for class UpdateTemplateInputBody.");

            if (content.IsSet && content.Value == null)
                throw new ArgumentNullException(nameof(content), "Property is not nullable for class UpdateTemplateInputBody.");

            if (subscriptionId.IsSet && subscriptionId.Value == null)
                throw new ArgumentNullException(nameof(subscriptionId), "Property is not nullable for class UpdateTemplateInputBody.");

            return new UpdateTemplateInputBody(name.Value!, schema, content, defaultChannels, subscriptionId);
        }

        /// <summary>
        /// Serializes a <see cref="UpdateTemplateInputBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateTemplateInputBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, UpdateTemplateInputBody updateTemplateInputBody, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, updateTemplateInputBody, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="UpdateTemplateInputBody" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="updateTemplateInputBody"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, UpdateTemplateInputBody updateTemplateInputBody, JsonSerializerOptions jsonSerializerOptions)
        {
            if (updateTemplateInputBody.Name == null)
                throw new ArgumentNullException(nameof(updateTemplateInputBody.Name), "Property is required for class UpdateTemplateInputBody.");

            if (updateTemplateInputBody.SchemaOption.IsSet && updateTemplateInputBody.Schema == null)
                throw new ArgumentNullException(nameof(updateTemplateInputBody.Schema), "Property is required for class UpdateTemplateInputBody.");

            if (updateTemplateInputBody.ContentOption.IsSet && updateTemplateInputBody.Content == null)
                throw new ArgumentNullException(nameof(updateTemplateInputBody.Content), "Property is required for class UpdateTemplateInputBody.");

            if (updateTemplateInputBody.SubscriptionIdOption.IsSet && updateTemplateInputBody.SubscriptionId == null)
                throw new ArgumentNullException(nameof(updateTemplateInputBody.SubscriptionId), "Property is required for class UpdateTemplateInputBody.");

            writer.WriteString("name", updateTemplateInputBody.Name);

            if (updateTemplateInputBody.SchemaOption.IsSet)
                writer.WriteString("$schema", updateTemplateInputBody.Schema);

            if (updateTemplateInputBody.ContentOption.IsSet)
            {
                writer.WritePropertyName("content");
                JsonSerializer.Serialize(writer, updateTemplateInputBody.Content, jsonSerializerOptions);
            }
            if (updateTemplateInputBody.DefaultChannelsOption.IsSet)
                if (updateTemplateInputBody.DefaultChannelsOption.Value != null)
                {
                    writer.WritePropertyName("default_channels");
                    JsonSerializer.Serialize(writer, updateTemplateInputBody.DefaultChannels, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("default_channels");
            if (updateTemplateInputBody.SubscriptionIdOption.IsSet)
                writer.WriteString("subscription_id", updateTemplateInputBody.SubscriptionId);
        }
    }
}
