apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - admin.yaml
  - send.yaml
  - dispatch.yaml
  - inbox.yaml
  - user.yaml
  - worker-events.yaml
  - worker-email.yaml
  - worker-sms.yaml
  - worker-inbox.yaml
