# coding: utf-8

"""
    Hermes Admin API

    Server-to-server API for managing subscription categories, templates, and notifications.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hermes_server_sdk.api.subscriptions_api import SubscriptionsApi


class TestSubscriptionsApi(unittest.TestCase):
    """SubscriptionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubscriptionsApi()

    def tearDown(self) -> None:
        pass

    def test_create_subscription(self) -> None:
        """Test case for create_subscription

        Create a subscription
        """
        pass

    def test_create_subscription_category(self) -> None:
        """Test case for create_subscription_category

        Create a subscription category
        """
        pass

    def test_delete_subscription(self) -> None:
        """Test case for delete_subscription

        Delete a subscription
        """
        pass

    def test_delete_subscription_category(self) -> None:
        """Test case for delete_subscription_category

        Delete a subscription category
        """
        pass

    def test_list_subscription_categories(self) -> None:
        """Test case for list_subscription_categories

        List subscription categories
        """
        pass

    def test_list_subscriptions(self) -> None:
        """Test case for list_subscriptions

        List subscriptions in a category
        """
        pass

    def test_update_subscription(self) -> None:
        """Test case for update_subscription

        Update a subscription
        """
        pass

    def test_update_subscription_category(self) -> None:
        """Test case for update_subscription_category

        Update a subscription category
        """
        pass


if __name__ == '__main__':
    unittest.main()
