# coding: utf-8

"""
    Hermes Admin API

    Server-to-server API for managing subscription categories, templates, and notifications.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hermes_server_sdk.models.tenant_item import TenantItem

class TestTenantItem(unittest.TestCase):
    """TenantItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TenantItem:
        """Test TenantItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TenantItem`
        """
        model = TenantItem()
        if include_optional:
            return TenantItem(
                var_schema = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                default_locale = '',
                id = '',
                name = '',
                user_count = 56
            )
        else:
            return TenantItem(
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                default_locale = '',
                id = '',
                name = '',
                user_count = 56,
        )
        """

    def testTenantItem(self):
        """Test TenantItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
