# coding: utf-8

"""
    Hermes Admin API

    Server-to-server API for managing subscription categories, templates, and notifications.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hermes_server_sdk.models.notification_item import NotificationItem

class TestNotificationItem(unittest.TestCase):
    """NotificationItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationItem:
        """Test NotificationItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationItem`
        """
        model = NotificationItem()
        if include_optional:
            return NotificationItem(
                body = '',
                category_id = '',
                channels = [
                    ''
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                status = '',
                template_id = '',
                template_slug = '',
                tenant_id = '',
                title = '',
                user_id = ''
            )
        else:
            return NotificationItem(
                body = '',
                category_id = '',
                channels = [
                    ''
                    ],
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                id = '',
                status = '',
                tenant_id = '',
                title = '',
                user_id = '',
        )
        """

    def testNotificationItem(self):
        """Test NotificationItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
