# coding: utf-8

"""
    Hermes Admin API

    Server-to-server API for managing subscription categories, templates, and notifications.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hermes_server_sdk.api.api_keys_api import APIKeysApi


class TestAPIKeysApi(unittest.TestCase):
    """APIKeysApi unit test stubs"""

    def setUp(self) -> None:
        self.api = APIKeysApi()

    def tearDown(self) -> None:
        pass

    def test_create_api_key(self) -> None:
        """Test case for create_api_key

        Create a new API key
        """
        pass

    def test_delete_api_key(self) -> None:
        """Test case for delete_api_key

        Revoke an API key
        """
        pass

    def test_list_api_keys(self) -> None:
        """Test case for list_api_keys

        List all API keys
        """
        pass


if __name__ == '__main__':
    unittest.main()
