# coding: utf-8

"""
    Hermes Admin API

    Server-to-server API for managing notification groups, types, and sending notifications.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hermes_server_sdk.models.notification_status_output_body import NotificationStatusOutputBody

class TestNotificationStatusOutputBody(unittest.TestCase):
    """NotificationStatusOutputBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> NotificationStatusOutputBody:
        """Test NotificationStatusOutputBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `NotificationStatusOutputBody`
        """
        model = NotificationStatusOutputBody()
        if include_optional:
            return NotificationStatusOutputBody(
                var_schema = '',
                events = [
                    hermes_server_sdk.models.notification_event.NotificationEvent(
                        channel = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        event = '', 
                        id = '', 
                        metadata = '', 
                        notification_id = '', 
                        severity = '', )
                    ],
                notification = hermes_server_sdk.models.notification.Notification(
                    action_label = '', 
                    action_url = '', 
                    archived_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    body = '', 
                    channels = [
                        ''
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    delivered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    group_id = '', 
                    id = '', 
                    idempotency_key = '', 
                    read_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    sent_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    status = '', 
                    tenant_id = '', 
                    title = '', 
                    type_id = '', 
                    user_id = '', )
            )
        else:
            return NotificationStatusOutputBody(
                events = [
                    hermes_server_sdk.models.notification_event.NotificationEvent(
                        channel = '', 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        event = '', 
                        id = '', 
                        metadata = '', 
                        notification_id = '', 
                        severity = '', )
                    ],
                notification = hermes_server_sdk.models.notification.Notification(
                    action_label = '', 
                    action_url = '', 
                    archived_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    body = '', 
                    channels = [
                        ''
                        ], 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    deleted_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    delivered_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    group_id = '', 
                    id = '', 
                    idempotency_key = '', 
                    read_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    sent_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    status = '', 
                    tenant_id = '', 
                    title = '', 
                    type_id = '', 
                    user_id = '', ),
        )
        """

    def testNotificationStatusOutputBody(self):
        """Test NotificationStatusOutputBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
