# coding: utf-8

"""
    Hermes Admin API

    Server-to-server API for managing subscription categories, templates, and notifications.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hermes_server_sdk.models.update_category_input_body import UpdateCategoryInputBody

class TestUpdateCategoryInputBody(unittest.TestCase):
    """UpdateCategoryInputBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UpdateCategoryInputBody:
        """Test UpdateCategoryInputBody
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UpdateCategoryInputBody`
        """
        model = UpdateCategoryInputBody()
        if include_optional:
            return UpdateCategoryInputBody(
                var_schema = '',
                default_channels = [
                    ''
                    ],
                default_state = 'on',
                name = '',
                sort_order = 56
            )
        else:
            return UpdateCategoryInputBody(
                default_channels = [
                    ''
                    ],
                default_state = 'on',
                name = '',
                sort_order = 56,
        )
        """

    def testUpdateCategoryInputBody(self):
        """Test UpdateCategoryInputBody"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
