# coding: utf-8

"""
    Hermes Admin API

    Server-to-server API for managing subscription categories, templates, and notifications.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hermes_server_sdk.api.templates_api import TemplatesApi


class TestTemplatesApi(unittest.TestCase):
    """TemplatesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TemplatesApi()

    def tearDown(self) -> None:
        pass

    def test_create_template(self) -> None:
        """Test case for create_template

        Create a notification template
        """
        pass

    def test_delete_template(self) -> None:
        """Test case for delete_template

        Delete a notification template
        """
        pass

    def test_list_templates(self) -> None:
        """Test case for list_templates

        List notification templates
        """
        pass

    def test_update_template(self) -> None:
        """Test case for update_template

        Update a notification template
        """
        pass


if __name__ == '__main__':
    unittest.main()
