# coding: utf-8

"""
    Hermes Admin API

    Server-to-server API for managing notification groups, types, and sending notifications.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hermes_server_sdk.api.groups_api import GroupsApi


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = GroupsApi()

    def tearDown(self) -> None:
        pass

    def test_create_group(self) -> None:
        """Test case for create_group

        Create a notification group
        """
        pass

    def test_list_groups(self) -> None:
        """Test case for list_groups

        List notification groups
        """
        pass

    def test_update_group(self) -> None:
        """Test case for update_group

        Update a notification group
        """
        pass


if __name__ == '__main__':
    unittest.main()
