/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hermes.ServerSdk.Model;
using Hermes.ServerSdk.Client;
using System.Reflection;

namespace Hermes.ServerSdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateCategoryInputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateCategoryInputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateCategoryInputBody
        //private CreateCategoryInputBody instance;

        public CreateCategoryInputBodyTests()
        {
            // TODO uncomment below to create an instance of CreateCategoryInputBody
            //instance = new CreateCategoryInputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateCategoryInputBody
        /// </summary>
        [Fact]
        public void CreateCategoryInputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateCategoryInputBody
            //Assert.IsType<CreateCategoryInputBody>(instance);
        }

        /// <summary>
        /// Test the property 'DefaultState'
        /// </summary>
        [Fact]
        public void DefaultStateTest()
        {
            // TODO unit test for the property 'DefaultState'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'DefaultChannels'
        /// </summary>
        [Fact]
        public void DefaultChannelsTest()
        {
            // TODO unit test for the property 'DefaultChannels'
        }

        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }
    }
}
