/*
 * Hermes Admin API
 *
 * Server-to-server API for managing notification groups, types, and sending notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hermes.ServerSdk.Model;
using Hermes.ServerSdk.Client;
using System.Reflection;

namespace Hermes.ServerSdk.Test.Model
{
    /// <summary>
    ///  Class for testing CreateGroupInputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateGroupInputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateGroupInputBody
        //private CreateGroupInputBody instance;

        public CreateGroupInputBodyTests()
        {
            // TODO uncomment below to create an instance of CreateGroupInputBody
            //instance = new CreateGroupInputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateGroupInputBody
        /// </summary>
        [Fact]
        public void CreateGroupInputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateGroupInputBody
            //Assert.IsType<CreateGroupInputBody>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Slug'
        /// </summary>
        [Fact]
        public void SlugTest()
        {
            // TODO unit test for the property 'Slug'
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }

        /// <summary>
        /// Test the property 'DefaultChannels'
        /// </summary>
        [Fact]
        public void DefaultChannelsTest()
        {
            // TODO unit test for the property 'DefaultChannels'
        }
    }
}
