/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hermes.ServerSdk.Model;
using Hermes.ServerSdk.Client;
using System.Reflection;

namespace Hermes.ServerSdk.Test.Model
{
    /// <summary>
    ///  Class for testing ListApiKeys429Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ListApiKeys429ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ListApiKeys429Response
        //private ListApiKeys429Response instance;

        public ListApiKeys429ResponseTests()
        {
            // TODO uncomment below to create an instance of ListApiKeys429Response
            //instance = new ListApiKeys429Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ListApiKeys429Response
        /// </summary>
        [Fact]
        public void ListApiKeys429ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ListApiKeys429Response
            //Assert.IsType<ListApiKeys429Response>(instance);
        }

        /// <summary>
        /// Test the property 'Error'
        /// </summary>
        [Fact]
        public void ErrorTest()
        {
            // TODO unit test for the property 'Error'
        }
    }
}
