/*
 * Hermes Admin API
 *
 * Server-to-server API for managing notification groups, types, and sending notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hermes.ServerSdk.Model;
using Hermes.ServerSdk.Client;
using System.Reflection;

namespace Hermes.ServerSdk.Test.Model
{
    /// <summary>
    ///  Class for testing NotificationEvent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NotificationEventTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NotificationEvent
        //private NotificationEvent instance;

        public NotificationEventTests()
        {
            // TODO uncomment below to create an instance of NotificationEvent
            //instance = new NotificationEvent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NotificationEvent
        /// </summary>
        [Fact]
        public void NotificationEventInstanceTest()
        {
            // TODO uncomment below to test "IsType" NotificationEvent
            //Assert.IsType<NotificationEvent>(instance);
        }

        /// <summary>
        /// Test the property 'Channel'
        /// </summary>
        [Fact]
        public void ChannelTest()
        {
            // TODO unit test for the property 'Channel'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Event'
        /// </summary>
        [Fact]
        public void EventTest()
        {
            // TODO unit test for the property 'Event'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'NotificationId'
        /// </summary>
        [Fact]
        public void NotificationIdTest()
        {
            // TODO unit test for the property 'NotificationId'
        }

        /// <summary>
        /// Test the property 'Severity'
        /// </summary>
        [Fact]
        public void SeverityTest()
        {
            // TODO unit test for the property 'Severity'
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }
    }
}
