/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hermes.ServerSdk.Model;
using Hermes.ServerSdk.Client;
using System.Reflection;

namespace Hermes.ServerSdk.Test.Model
{
    /// <summary>
    ///  Class for testing SendInputBodyMetadata
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendInputBodyMetadataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendInputBodyMetadata
        //private SendInputBodyMetadata instance;

        public SendInputBodyMetadataTests()
        {
            // TODO uncomment below to create an instance of SendInputBodyMetadata
            //instance = new SendInputBodyMetadata();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendInputBodyMetadata
        /// </summary>
        [Fact]
        public void SendInputBodyMetadataInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendInputBodyMetadata
            //Assert.IsType<SendInputBodyMetadata>(instance);
        }

        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }

        /// <summary>
        /// Test the property 'Toast'
        /// </summary>
        [Fact]
        public void ToastTest()
        {
            // TODO unit test for the property 'Toast'
        }
    }
}
