/*
 * Hermes Admin API
 *
 * Server-to-server API for managing notification groups, types, and sending notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hermes.ServerSdk.Model;
using Hermes.ServerSdk.Client;
using System.Reflection;

namespace Hermes.ServerSdk.Test.Model
{
    /// <summary>
    ///  Class for testing SendContent
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SendContentTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SendContent
        //private SendContent instance;

        public SendContentTests()
        {
            // TODO uncomment below to create an instance of SendContent
            //instance = new SendContent();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SendContent
        /// </summary>
        [Fact]
        public void SendContentInstanceTest()
        {
            // TODO uncomment below to test "IsType" SendContent
            //Assert.IsType<SendContent>(instance);
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'ActionLabel'
        /// </summary>
        [Fact]
        public void ActionLabelTest()
        {
            // TODO unit test for the property 'ActionLabel'
        }

        /// <summary>
        /// Test the property 'ActionUrl'
        /// </summary>
        [Fact]
        public void ActionUrlTest()
        {
            // TODO unit test for the property 'ActionUrl'
        }
    }
}
