/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Hermes.ServerSdk.Model;
using Hermes.ServerSdk.Client;
using System.Reflection;

namespace Hermes.ServerSdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateSubscriptionInputBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateSubscriptionInputBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateSubscriptionInputBody
        //private UpdateSubscriptionInputBody instance;

        public UpdateSubscriptionInputBodyTests()
        {
            // TODO uncomment below to create an instance of UpdateSubscriptionInputBody
            //instance = new UpdateSubscriptionInputBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateSubscriptionInputBody
        /// </summary>
        [Fact]
        public void UpdateSubscriptionInputBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateSubscriptionInputBody
            //Assert.IsType<UpdateSubscriptionInputBody>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'SortOrder'
        /// </summary>
        [Fact]
        public void SortOrderTest()
        {
            // TODO unit test for the property 'SortOrder'
        }

        /// <summary>
        /// Test the property 'Schema'
        /// </summary>
        [Fact]
        public void SchemaTest()
        {
            // TODO unit test for the property 'Schema'
        }
    }
}
