/*
 * Hermes Admin API
 * Server-to-server API for managing notification groups, types, and sending notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hermes.sdk.api;

import com.hermes.sdk.ApiException;
import com.hermes.sdk.model.CreateGroupInputBody;
import com.hermes.sdk.model.ErrorModel;
import com.hermes.sdk.model.NotificationGroup;
import com.hermes.sdk.model.UpdateGroupInputBody;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for GroupsApi
 */
@Disabled
public class GroupsApiTest {

    private final GroupsApi api = new GroupsApi();

    /**
     * Create a notification group
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createGroupTest() throws ApiException {
        CreateGroupInputBody createGroupInputBody = null;
        NotificationGroup response = api.createGroup(createGroupInputBody);
        // TODO: test validations
    }

    /**
     * List notification groups
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listGroupsTest() throws ApiException {
        List<NotificationGroup> response = api.listGroups();
        // TODO: test validations
    }

    /**
     * Update a notification group
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void updateGroupTest() throws ApiException {
        String id = null;
        UpdateGroupInputBody updateGroupInputBody = null;
        NotificationGroup response = api.updateGroup(id, updateGroupInputBody);
        // TODO: test validations
    }

}
