/*
 * Hermes Admin API
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hermes.sdk.api;

import com.hermes.sdk.ApiException;
import com.hermes.sdk.model.CreateOrganizationInputBody;
import com.hermes.sdk.model.ErrorModel;
import com.hermes.sdk.model.OrganizationItem;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for OrganizationsApi
 */
@Disabled
public class OrganizationsApiTest {

    private final OrganizationsApi api = new OrganizationsApi();

    /**
     * Create an organization
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createOrganizationTest() throws ApiException {
        CreateOrganizationInputBody createOrganizationInputBody = null;
        OrganizationItem response = api.createOrganization(createOrganizationInputBody);
        // TODO: test validations
    }

    /**
     * List organizations
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listOrganizationsTest() throws ApiException {
        List<OrganizationItem> response = api.listOrganizations();
        // TODO: test validations
    }

}
