export {
  Hermes,
  CategoriesService,
  SubscriptionsService,
  TemplatesService,
  NotificationsService,
  AuthService,
  APIKeysService,
  TenantsService,
  UsersService,
  HermesError,
  type HermesConfig,
  type SendOptions,
  type SubscriptionCategory,
  type Subscription,
  type NotificationTemplate,
  type Notification,
  type NotificationEvent,
  type APIKeyInfo,
  type APIKeyCreated,
  type Tenant,
  type User,
} from "./client.js";
