apiVersion: apps/v1
kind: Deployment
metadata:
  name: centrifugo
spec:
  template:
    spec:
      containers:
        - name: centrifugo
          env:
            - name: CENTRIFUGO_TOKEN_HMAC_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: hermes-secrets
                  key: HERMES_CENTRIFUGO_TOKEN_SECRET
            - name: CENTRIFUGO_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hermes-secrets
                  key: HERMES_CENTRIFUGO_API_KEY
            - name: CENTRIFUGO_REDIS_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: hermes-secrets
                  key: HERMES_CENTRIFUGO_REDIS_ADDRESS
