apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

labels:
  - pairs:
      app.kubernetes.io/part-of: hermes
      app.kubernetes.io/component: observability
    includeSelectors: false

resources:
  - namespace.yaml
  - kube-prometheus-stack/
  - loki/
  - tempo/
  - otel-collector/
  - alloy/
  - exporters/
  - grafana/
  - prometheus-rules/
