/*
 * Hermes Admin API
 * Server-to-server API for managing notification groups, types, and sending notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hermes.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hermes.sdk.JSON;

/**
 * NotificationType
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-03-22T18:24:04.702920-04:00[America/Toronto]", comments = "Generator version: 7.20.0")
public class NotificationType {
  public static final String SERIALIZED_NAME_$_SCHEMA = "$schema";
  @SerializedName(SERIALIZED_NAME_$_SCHEMA)
  @javax.annotation.Nullable
  private URI $schema;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_EMAIL_BODY = "email_body";
  @SerializedName(SERIALIZED_NAME_EMAIL_BODY)
  @javax.annotation.Nullable
  private String emailBody;

  public static final String SERIALIZED_NAME_EMAIL_SUBJECT = "email_subject";
  @SerializedName(SERIALIZED_NAME_EMAIL_SUBJECT)
  @javax.annotation.Nullable
  private String emailSubject;

  public static final String SERIALIZED_NAME_GROUP_ID = "group_id";
  @SerializedName(SERIALIZED_NAME_GROUP_ID)
  @javax.annotation.Nonnull
  private String groupId;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_INBOX_BODY = "inbox_body";
  @SerializedName(SERIALIZED_NAME_INBOX_BODY)
  @javax.annotation.Nullable
  private String inboxBody;

  public static final String SERIALIZED_NAME_INBOX_TITLE = "inbox_title";
  @SerializedName(SERIALIZED_NAME_INBOX_TITLE)
  @javax.annotation.Nullable
  private String inboxTitle;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  @javax.annotation.Nonnull
  private String slug;

  public static final String SERIALIZED_NAME_SMS_BODY = "sms_body";
  @SerializedName(SERIALIZED_NAME_SMS_BODY)
  @javax.annotation.Nullable
  private String smsBody;

  public NotificationType() {
  }

  public NotificationType(
     URI $schema
  ) {
    this();
    this.$schema = $schema;
  }

  /**
   * A URL to the JSON Schema for this object.
   * @return $schema
   */
  @javax.annotation.Nullable
  public URI get$Schema() {
    return $schema;
  }



  public NotificationType createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public NotificationType emailBody(@javax.annotation.Nullable String emailBody) {
    this.emailBody = emailBody;
    return this;
  }

  /**
   * Get emailBody
   * @return emailBody
   */
  @javax.annotation.Nullable
  public String getEmailBody() {
    return emailBody;
  }

  public void setEmailBody(@javax.annotation.Nullable String emailBody) {
    this.emailBody = emailBody;
  }


  public NotificationType emailSubject(@javax.annotation.Nullable String emailSubject) {
    this.emailSubject = emailSubject;
    return this;
  }

  /**
   * Get emailSubject
   * @return emailSubject
   */
  @javax.annotation.Nullable
  public String getEmailSubject() {
    return emailSubject;
  }

  public void setEmailSubject(@javax.annotation.Nullable String emailSubject) {
    this.emailSubject = emailSubject;
  }


  public NotificationType groupId(@javax.annotation.Nonnull String groupId) {
    this.groupId = groupId;
    return this;
  }

  /**
   * Get groupId
   * @return groupId
   */
  @javax.annotation.Nonnull
  public String getGroupId() {
    return groupId;
  }

  public void setGroupId(@javax.annotation.Nonnull String groupId) {
    this.groupId = groupId;
  }


  public NotificationType id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public NotificationType inboxBody(@javax.annotation.Nullable String inboxBody) {
    this.inboxBody = inboxBody;
    return this;
  }

  /**
   * Get inboxBody
   * @return inboxBody
   */
  @javax.annotation.Nullable
  public String getInboxBody() {
    return inboxBody;
  }

  public void setInboxBody(@javax.annotation.Nullable String inboxBody) {
    this.inboxBody = inboxBody;
  }


  public NotificationType inboxTitle(@javax.annotation.Nullable String inboxTitle) {
    this.inboxTitle = inboxTitle;
    return this;
  }

  /**
   * Get inboxTitle
   * @return inboxTitle
   */
  @javax.annotation.Nullable
  public String getInboxTitle() {
    return inboxTitle;
  }

  public void setInboxTitle(@javax.annotation.Nullable String inboxTitle) {
    this.inboxTitle = inboxTitle;
  }


  public NotificationType name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public NotificationType slug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @javax.annotation.Nonnull
  public String getSlug() {
    return slug;
  }

  public void setSlug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
  }


  public NotificationType smsBody(@javax.annotation.Nullable String smsBody) {
    this.smsBody = smsBody;
    return this;
  }

  /**
   * Get smsBody
   * @return smsBody
   */
  @javax.annotation.Nullable
  public String getSmsBody() {
    return smsBody;
  }

  public void setSmsBody(@javax.annotation.Nullable String smsBody) {
    this.smsBody = smsBody;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationType notificationType = (NotificationType) o;
    return Objects.equals(this.$schema, notificationType.$schema) &&
        Objects.equals(this.createdAt, notificationType.createdAt) &&
        Objects.equals(this.emailBody, notificationType.emailBody) &&
        Objects.equals(this.emailSubject, notificationType.emailSubject) &&
        Objects.equals(this.groupId, notificationType.groupId) &&
        Objects.equals(this.id, notificationType.id) &&
        Objects.equals(this.inboxBody, notificationType.inboxBody) &&
        Objects.equals(this.inboxTitle, notificationType.inboxTitle) &&
        Objects.equals(this.name, notificationType.name) &&
        Objects.equals(this.slug, notificationType.slug) &&
        Objects.equals(this.smsBody, notificationType.smsBody);
  }

  @Override
  public int hashCode() {
    return Objects.hash($schema, createdAt, emailBody, emailSubject, groupId, id, inboxBody, inboxTitle, name, slug, smsBody);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationType {\n");
    sb.append("    $schema: ").append(toIndentedString($schema)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    emailBody: ").append(toIndentedString(emailBody)).append("\n");
    sb.append("    emailSubject: ").append(toIndentedString(emailSubject)).append("\n");
    sb.append("    groupId: ").append(toIndentedString(groupId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    inboxBody: ").append(toIndentedString(inboxBody)).append("\n");
    sb.append("    inboxTitle: ").append(toIndentedString(inboxTitle)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    smsBody: ").append(toIndentedString(smsBody)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("$schema", "created_at", "email_body", "email_subject", "group_id", "id", "inbox_body", "inbox_title", "name", "slug", "sms_body"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("created_at", "group_id", "id", "name", "slug"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to NotificationType
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!NotificationType.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in NotificationType is not found in the empty JSON string", NotificationType.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!NotificationType.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `NotificationType` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : NotificationType.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("$schema") != null && !jsonObj.get("$schema").isJsonNull()) && !jsonObj.get("$schema").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `$schema` to be a primitive type in the JSON string but got `%s`", jsonObj.get("$schema").toString()));
      }
      if ((jsonObj.get("email_body") != null && !jsonObj.get("email_body").isJsonNull()) && !jsonObj.get("email_body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email_body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email_body").toString()));
      }
      if ((jsonObj.get("email_subject") != null && !jsonObj.get("email_subject").isJsonNull()) && !jsonObj.get("email_subject").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `email_subject` to be a primitive type in the JSON string but got `%s`", jsonObj.get("email_subject").toString()));
      }
      if (!jsonObj.get("group_id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `group_id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("group_id").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("inbox_body") != null && !jsonObj.get("inbox_body").isJsonNull()) && !jsonObj.get("inbox_body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `inbox_body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("inbox_body").toString()));
      }
      if ((jsonObj.get("inbox_title") != null && !jsonObj.get("inbox_title").isJsonNull()) && !jsonObj.get("inbox_title").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `inbox_title` to be a primitive type in the JSON string but got `%s`", jsonObj.get("inbox_title").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("slug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `slug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("slug").toString()));
      }
      if ((jsonObj.get("sms_body") != null && !jsonObj.get("sms_body").isJsonNull()) && !jsonObj.get("sms_body").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `sms_body` to be a primitive type in the JSON string but got `%s`", jsonObj.get("sms_body").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!NotificationType.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'NotificationType' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<NotificationType> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(NotificationType.class));

       return (TypeAdapter<T>) new TypeAdapter<NotificationType>() {
           @Override
           public void write(JsonWriter out, NotificationType value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public NotificationType read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of NotificationType given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of NotificationType
   * @throws IOException if the JSON string is invalid with respect to NotificationType
   */
  public static NotificationType fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, NotificationType.class);
  }

  /**
   * Convert an instance of NotificationType to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

