/*
 * Hermes Admin API
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hermes.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hermes.sdk.JSON;

/**
 * SubscriptionCategory
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-07-28T00:22:36.554995430Z[Etc/UTC]", comments = "Generator version: 7.20.0")
public class SubscriptionCategory {
  public static final String SERIALIZED_NAME_$_SCHEMA = "$schema";
  @SerializedName(SERIALIZED_NAME_$_SCHEMA)
  @javax.annotation.Nullable
  private URI $schema;

  public static final String SERIALIZED_NAME_CREATED_AT = "created_at";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DEFAULT_CHANNELS = "default_channels";
  @SerializedName(SERIALIZED_NAME_DEFAULT_CHANNELS)
  @javax.annotation.Nullable
  private List<String> defaultChannels;

  public static final String SERIALIZED_NAME_DEFAULT_STATE = "default_state";
  @SerializedName(SERIALIZED_NAME_DEFAULT_STATE)
  @javax.annotation.Nonnull
  private String defaultState;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nonnull
  private String id;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_SLUG = "slug";
  @SerializedName(SERIALIZED_NAME_SLUG)
  @javax.annotation.Nonnull
  private String slug;

  public static final String SERIALIZED_NAME_SORT_ORDER = "sort_order";
  @SerializedName(SERIALIZED_NAME_SORT_ORDER)
  @javax.annotation.Nonnull
  private Long sortOrder;

  public SubscriptionCategory() {
  }

  public SubscriptionCategory(
     URI $schema
  ) {
    this();
    this.$schema = $schema;
  }

  /**
   * A URL to the JSON Schema for this object.
   * @return $schema
   */
  @javax.annotation.Nullable
  public URI get$Schema() {
    return $schema;
  }



  public SubscriptionCategory createdAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @javax.annotation.Nonnull
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(@javax.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public SubscriptionCategory defaultChannels(@javax.annotation.Nullable List<String> defaultChannels) {
    this.defaultChannels = defaultChannels;
    return this;
  }

  public SubscriptionCategory addDefaultChannelsItem(String defaultChannelsItem) {
    if (this.defaultChannels == null) {
      this.defaultChannels = new ArrayList<>();
    }
    this.defaultChannels.add(defaultChannelsItem);
    return this;
  }

  /**
   * Get defaultChannels
   * @return defaultChannels
   */
  @javax.annotation.Nullable
  public List<String> getDefaultChannels() {
    return defaultChannels;
  }

  public void setDefaultChannels(@javax.annotation.Nullable List<String> defaultChannels) {
    this.defaultChannels = defaultChannels;
  }


  public SubscriptionCategory defaultState(@javax.annotation.Nonnull String defaultState) {
    this.defaultState = defaultState;
    return this;
  }

  /**
   * Get defaultState
   * @return defaultState
   */
  @javax.annotation.Nonnull
  public String getDefaultState() {
    return defaultState;
  }

  public void setDefaultState(@javax.annotation.Nonnull String defaultState) {
    this.defaultState = defaultState;
  }


  public SubscriptionCategory id(@javax.annotation.Nonnull String id) {
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @javax.annotation.Nonnull
  public String getId() {
    return id;
  }

  public void setId(@javax.annotation.Nonnull String id) {
    this.id = id;
  }


  public SubscriptionCategory name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public SubscriptionCategory slug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
    return this;
  }

  /**
   * Get slug
   * @return slug
   */
  @javax.annotation.Nonnull
  public String getSlug() {
    return slug;
  }

  public void setSlug(@javax.annotation.Nonnull String slug) {
    this.slug = slug;
  }


  public SubscriptionCategory sortOrder(@javax.annotation.Nonnull Long sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

  /**
   * Get sortOrder
   * @return sortOrder
   */
  @javax.annotation.Nonnull
  public Long getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(@javax.annotation.Nonnull Long sortOrder) {
    this.sortOrder = sortOrder;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SubscriptionCategory subscriptionCategory = (SubscriptionCategory) o;
    return Objects.equals(this.$schema, subscriptionCategory.$schema) &&
        Objects.equals(this.createdAt, subscriptionCategory.createdAt) &&
        Objects.equals(this.defaultChannels, subscriptionCategory.defaultChannels) &&
        Objects.equals(this.defaultState, subscriptionCategory.defaultState) &&
        Objects.equals(this.id, subscriptionCategory.id) &&
        Objects.equals(this.name, subscriptionCategory.name) &&
        Objects.equals(this.slug, subscriptionCategory.slug) &&
        Objects.equals(this.sortOrder, subscriptionCategory.sortOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash($schema, createdAt, defaultChannels, defaultState, id, name, slug, sortOrder);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SubscriptionCategory {\n");
    sb.append("    $schema: ").append(toIndentedString($schema)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    defaultChannels: ").append(toIndentedString(defaultChannels)).append("\n");
    sb.append("    defaultState: ").append(toIndentedString(defaultState)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    slug: ").append(toIndentedString(slug)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("$schema", "created_at", "default_channels", "default_state", "id", "name", "slug", "sort_order"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("created_at", "default_channels", "default_state", "id", "name", "slug", "sort_order"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to SubscriptionCategory
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!SubscriptionCategory.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in SubscriptionCategory is not found in the empty JSON string", SubscriptionCategory.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!SubscriptionCategory.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `SubscriptionCategory` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : SubscriptionCategory.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("$schema") != null && !jsonObj.get("$schema").isJsonNull()) && !jsonObj.get("$schema").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `$schema` to be a primitive type in the JSON string but got `%s`", jsonObj.get("$schema").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("default_channels") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("default_channels").isJsonArray() && !jsonObj.get("default_channels").isJsonNull()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `default_channels` to be an array in the JSON string but got `%s`", jsonObj.get("default_channels").toString()));
      }
      if (!jsonObj.get("default_state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `default_state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_state").toString()));
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
      if (!jsonObj.get("slug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `slug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("slug").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!SubscriptionCategory.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'SubscriptionCategory' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<SubscriptionCategory> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(SubscriptionCategory.class));

       return (TypeAdapter<T>) new TypeAdapter<SubscriptionCategory>() {
           @Override
           public void write(JsonWriter out, SubscriptionCategory value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public SubscriptionCategory read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of SubscriptionCategory given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of SubscriptionCategory
   * @throws IOException if the JSON string is invalid with respect to SubscriptionCategory
   */
  public static SubscriptionCategory fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, SubscriptionCategory.class);
  }

  /**
   * Convert an instance of SubscriptionCategory to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

