/*
 * Hermes Admin API
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.hermes.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.hermes.sdk.JSON;

/**
 * UpdateCategoryInputBody
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-15T19:42:17.343876-04:00[America/Toronto]", comments = "Generator version: 7.20.0")
public class UpdateCategoryInputBody {
  public static final String SERIALIZED_NAME_$_SCHEMA = "$schema";
  @SerializedName(SERIALIZED_NAME_$_SCHEMA)
  @javax.annotation.Nullable
  private URI $schema;

  public static final String SERIALIZED_NAME_DEFAULT_CHANNELS = "default_channels";
  @SerializedName(SERIALIZED_NAME_DEFAULT_CHANNELS)
  @javax.annotation.Nullable
  private List<String> defaultChannels;

  /**
   * Default subscription state
   */
  @JsonAdapter(DefaultStateEnum.Adapter.class)
  public enum DefaultStateEnum {
    ON("on"),
    
    OFF("off"),
    
    REQUIRED("required");

    private String value;

    DefaultStateEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static DefaultStateEnum fromValue(String value) {
      for (DefaultStateEnum b : DefaultStateEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<DefaultStateEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final DefaultStateEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public DefaultStateEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return DefaultStateEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      DefaultStateEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_DEFAULT_STATE = "default_state";
  @SerializedName(SERIALIZED_NAME_DEFAULT_STATE)
  @javax.annotation.Nonnull
  private DefaultStateEnum defaultState;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  @javax.annotation.Nonnull
  private String name;

  public static final String SERIALIZED_NAME_SORT_ORDER = "sort_order";
  @SerializedName(SERIALIZED_NAME_SORT_ORDER)
  @javax.annotation.Nonnull
  private Long sortOrder;

  public UpdateCategoryInputBody() {
  }

  public UpdateCategoryInputBody(
     URI $schema
  ) {
    this();
    this.$schema = $schema;
  }

  /**
   * A URL to the JSON Schema for this object.
   * @return $schema
   */
  @javax.annotation.Nullable
  public URI get$Schema() {
    return $schema;
  }



  public UpdateCategoryInputBody defaultChannels(@javax.annotation.Nullable List<String> defaultChannels) {
    this.defaultChannels = defaultChannels;
    return this;
  }

  public UpdateCategoryInputBody addDefaultChannelsItem(String defaultChannelsItem) {
    if (this.defaultChannels == null) {
      this.defaultChannels = new ArrayList<>();
    }
    this.defaultChannels.add(defaultChannelsItem);
    return this;
  }

  /**
   * Default delivery channels
   * @return defaultChannels
   */
  @javax.annotation.Nullable
  public List<String> getDefaultChannels() {
    return defaultChannels;
  }

  public void setDefaultChannels(@javax.annotation.Nullable List<String> defaultChannels) {
    this.defaultChannels = defaultChannels;
  }


  public UpdateCategoryInputBody defaultState(@javax.annotation.Nonnull DefaultStateEnum defaultState) {
    this.defaultState = defaultState;
    return this;
  }

  /**
   * Default subscription state
   * @return defaultState
   */
  @javax.annotation.Nonnull
  public DefaultStateEnum getDefaultState() {
    return defaultState;
  }

  public void setDefaultState(@javax.annotation.Nonnull DefaultStateEnum defaultState) {
    this.defaultState = defaultState;
  }


  public UpdateCategoryInputBody name(@javax.annotation.Nonnull String name) {
    this.name = name;
    return this;
  }

  /**
   * Human-readable name
   * @return name
   */
  @javax.annotation.Nonnull
  public String getName() {
    return name;
  }

  public void setName(@javax.annotation.Nonnull String name) {
    this.name = name;
  }


  public UpdateCategoryInputBody sortOrder(@javax.annotation.Nonnull Long sortOrder) {
    this.sortOrder = sortOrder;
    return this;
  }

  /**
   * Display order
   * @return sortOrder
   */
  @javax.annotation.Nonnull
  public Long getSortOrder() {
    return sortOrder;
  }

  public void setSortOrder(@javax.annotation.Nonnull Long sortOrder) {
    this.sortOrder = sortOrder;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateCategoryInputBody updateCategoryInputBody = (UpdateCategoryInputBody) o;
    return Objects.equals(this.$schema, updateCategoryInputBody.$schema) &&
        Objects.equals(this.defaultChannels, updateCategoryInputBody.defaultChannels) &&
        Objects.equals(this.defaultState, updateCategoryInputBody.defaultState) &&
        Objects.equals(this.name, updateCategoryInputBody.name) &&
        Objects.equals(this.sortOrder, updateCategoryInputBody.sortOrder);
  }

  @Override
  public int hashCode() {
    return Objects.hash($schema, defaultChannels, defaultState, name, sortOrder);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateCategoryInputBody {\n");
    sb.append("    $schema: ").append(toIndentedString($schema)).append("\n");
    sb.append("    defaultChannels: ").append(toIndentedString(defaultChannels)).append("\n");
    sb.append("    defaultState: ").append(toIndentedString(defaultState)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    sortOrder: ").append(toIndentedString(sortOrder)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("$schema", "default_channels", "default_state", "name", "sort_order"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("default_channels", "default_state", "name", "sort_order"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to UpdateCategoryInputBody
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!UpdateCategoryInputBody.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in UpdateCategoryInputBody is not found in the empty JSON string", UpdateCategoryInputBody.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!UpdateCategoryInputBody.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `UpdateCategoryInputBody` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : UpdateCategoryInputBody.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("$schema") != null && !jsonObj.get("$schema").isJsonNull()) && !jsonObj.get("$schema").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `$schema` to be a primitive type in the JSON string but got `%s`", jsonObj.get("$schema").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("default_channels") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("default_channels").isJsonArray() && !jsonObj.get("default_channels").isJsonNull()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `default_channels` to be an array in the JSON string but got `%s`", jsonObj.get("default_channels").toString()));
      }
      if (!jsonObj.get("default_state").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `default_state` to be a primitive type in the JSON string but got `%s`", jsonObj.get("default_state").toString()));
      }
      // validate the required field `default_state`
      DefaultStateEnum.validateJsonElement(jsonObj.get("default_state"));
      if (!jsonObj.get("name").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `name` to be a primitive type in the JSON string but got `%s`", jsonObj.get("name").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!UpdateCategoryInputBody.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'UpdateCategoryInputBody' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<UpdateCategoryInputBody> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(UpdateCategoryInputBody.class));

       return (TypeAdapter<T>) new TypeAdapter<UpdateCategoryInputBody>() {
           @Override
           public void write(JsonWriter out, UpdateCategoryInputBody value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public UpdateCategoryInputBody read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of UpdateCategoryInputBody given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of UpdateCategoryInputBody
   * @throws IOException if the JSON string is invalid with respect to UpdateCategoryInputBody
   */
  public static UpdateCategoryInputBody fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, UpdateCategoryInputBody.class);
  }

  /**
   * Convert an instance of UpdateCategoryInputBody to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

