/*
 * Hermes Admin API
 *
 * Server-to-server API for managing subscription categories, templates, and notifications.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Net.Http;
using Microsoft.Extensions.DependencyInjection;
using Hermes.ServerSdk.Api;
using Hermes.ServerSdk.Model;

namespace Hermes.ServerSdk.Client
{
    /// <summary>
    /// Provides hosting configuration for Hermes.ServerSdk
    /// </summary>
    public class HostConfiguration
    {
        private readonly IServiceCollection _services;
        private readonly JsonSerializerOptions _jsonOptions = new JsonSerializerOptions();

        internal bool HttpClientsAdded { get; private set; }

        /// <summary>
        /// Instantiates the class 
        /// </summary>
        /// <param name="services"></param>
        public HostConfiguration(IServiceCollection services)
        {
            _services = services;
            _jsonOptions.Converters.Add(new JsonStringEnumConverter());
            _jsonOptions.Converters.Add(new DateTimeJsonConverter());
            _jsonOptions.Converters.Add(new DateTimeNullableJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyJsonConverter());
            _jsonOptions.Converters.Add(new DateOnlyNullableJsonConverter());
            _jsonOptions.Converters.Add(new ApiKeyCreatedOutputBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateAPIKeyInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateCategoryInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateOrganizationInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateSubscriptionInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new CreateTemplateInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new ErrorDetailJsonConverter());
            _jsonOptions.Converters.Add(new ErrorModelJsonConverter());
            _jsonOptions.Converters.Add(new ItemJsonConverter());
            _jsonOptions.Converters.Add(new NotificationJsonConverter());
            _jsonOptions.Converters.Add(new NotificationEventJsonConverter());
            _jsonOptions.Converters.Add(new NotificationItemJsonConverter());
            _jsonOptions.Converters.Add(new NotificationStatusOutputBodyJsonConverter());
            _jsonOptions.Converters.Add(new NotificationTemplateJsonConverter());
            _jsonOptions.Converters.Add(new OrganizationItemJsonConverter());
            _jsonOptions.Converters.Add(new SendContentJsonConverter());
            _jsonOptions.Converters.Add(new SendInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new SendOutputBodyJsonConverter());
            _jsonOptions.Converters.Add(new SendRecipientJsonConverter());
            _jsonOptions.Converters.Add(new SubscriptionJsonConverter());
            _jsonOptions.Converters.Add(new SubscriptionCategoryJsonConverter());
            _jsonOptions.Converters.Add(new TokenInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new TokenOutputBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateCategoryInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateSubscriptionInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new UpdateTemplateInputBodyJsonConverter());
            _jsonOptions.Converters.Add(new UserItemJsonConverter());
            JsonSerializerOptionsProvider jsonSerializerOptionsProvider = new(_jsonOptions);
            _services.AddSingleton(jsonSerializerOptionsProvider);
            _services.AddSingleton<IApiFactory, ApiFactory>();
            _services.AddSingleton<APIKeysApiEvents>();
            _services.AddSingleton<AuthApiEvents>();
            _services.AddSingleton<NotificationsApiEvents>();
            _services.AddSingleton<OrganizationsApiEvents>();
            _services.AddSingleton<SubscriptionsApiEvents>();
            _services.AddSingleton<TemplatesApiEvents>();
            _services.AddSingleton<UsersApiEvents>();
        }

        /// <summary>
        /// Configures the HttpClients.
        /// </summary>
        /// <param name="client"></param>
        /// <param name="builder"></param>
        /// <returns></returns>
        public HostConfiguration AddApiHttpClients
        (
            Action<HttpClient>? client = null, Action<IHttpClientBuilder>? builder = null)
        {
            if (client == null)
                client = c => c.BaseAddress = new Uri(ClientUtils.BASE_ADDRESS);

            List<IHttpClientBuilder> builders = new List<IHttpClientBuilder>();

            builders.Add(_services.AddHttpClient<IAPIKeysApi, APIKeysApi>("Hermes.ServerSdk.Api.IAPIKeysApi", client));
            builders.Add(_services.AddHttpClient<IAuthApi, AuthApi>("Hermes.ServerSdk.Api.IAuthApi", client));
            builders.Add(_services.AddHttpClient<INotificationsApi, NotificationsApi>("Hermes.ServerSdk.Api.INotificationsApi", client));
            builders.Add(_services.AddHttpClient<IOrganizationsApi, OrganizationsApi>("Hermes.ServerSdk.Api.IOrganizationsApi", client));
            builders.Add(_services.AddHttpClient<ISubscriptionsApi, SubscriptionsApi>("Hermes.ServerSdk.Api.ISubscriptionsApi", client));
            builders.Add(_services.AddHttpClient<ITemplatesApi, TemplatesApi>("Hermes.ServerSdk.Api.ITemplatesApi", client));
            builders.Add(_services.AddHttpClient<IUsersApi, UsersApi>("Hermes.ServerSdk.Api.IUsersApi", client));
            
            if (builder != null)
                foreach (IHttpClientBuilder instance in builders)
                    builder(instance);

            HttpClientsAdded = true;

            return this;
        }

        /// <summary>
        /// Configures the JsonSerializerSettings
        /// </summary>
        /// <param name="options"></param>
        /// <returns></returns>
        public HostConfiguration ConfigureJsonOptions(Action<JsonSerializerOptions> options)
        {
            options(_jsonOptions);

            return this;
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="token"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(TTokenBase token) where TTokenBase : TokenBase
        {
            return AddTokens(new TTokenBase[]{ token });
        }

        /// <summary>
        /// Adds tokens to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <param name="tokens"></param>
        /// <returns></returns>
        public HostConfiguration AddTokens<TTokenBase>(IEnumerable<TTokenBase> tokens) where TTokenBase : TokenBase
        {
            TokenContainer<TTokenBase> container = new TokenContainer<TTokenBase>(tokens);
            _services.AddSingleton(services => container);

            return this;
        }

        /// <summary>
        /// Adds a token provider to your IServiceCollection
        /// </summary>
        /// <typeparam name="TTokenProvider"></typeparam>
        /// <typeparam name="TTokenBase"></typeparam>
        /// <returns></returns>
        public HostConfiguration UseProvider<TTokenProvider, TTokenBase>() 
            where TTokenProvider : TokenProvider<TTokenBase>
            where TTokenBase : TokenBase
        {
            _services.AddSingleton<TTokenProvider>();
            _services.AddSingleton<TokenProvider<TTokenBase>>(services => services.GetRequiredService<TTokenProvider>());

            return this;
        }
    }
}
